server:
  port: 8081

# custom path for api docs
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method

spring:

  application:
    name: delivery-service

holiday-external-client-url: https://holidayapi.com/v1/holidays?pretty&country={countryCode}&year={year}&key=54c7bf0e-f5ea-4f1a-9ae8-3c90819d9184

logging:
  level:
    org.springframework: INFO
    com.tascigorkem.linkconverterservice: DEBUG
  # output to a file
  file.name: app.log
  pattern.file: '%d %p %c{1.} [%t] %m%n'
  pattern.console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'

---
spring:
  profiles: local

---
spring:
  profiles: docker

